name: End to End Test - .NET Isolated/Func V4

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/e2e/**'
      - 'Directory.Build.targets'
      - 'Directory.Packages.props'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'src/**'
      - 'test/e2e/**'
      - 'Directory.Build.targets'
      - 'Directory.Packages.props'

jobs:
  e2e-azurestorage-linux:
    runs-on: ubuntu-latest
    env:
      E2E_TEST_DURABLE_BACKEND: 'AzureStorage'
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Set up Node.js (needed for Azurite)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Azurite requires at least Node 18

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup E2E tests
        shell: pwsh
        run: |
          .\test\e2e\Tests\build-e2e-test.ps1

      - name: Build Test Project
        working-directory: test/e2e/Tests
        run: dotnet build

      - name: Setup Environment for dotnet
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=dotnet-isolated"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicDotNetIsolated"

      - name: Run E2E tests (dotnet-isolated)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'AzureStorage!=Skip&Dotnet!=Skip&Dotnet-AzureStorage!=Skip'

      - name: Setup Environment for PowerShell
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=powershell"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicPowerShell"

      - name: Run E2E tests (PowerShell)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'AzureStorage!=Skip&PowerShell!=Skip&PowerShell-AzureStorage!=Skip'

      - name: Setup Environment for Python
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=python"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicPython"

      - name: Run E2E tests (Python)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'AzureStorage!=Skip&Python!=Skip&Python-AzureStorage!=Skip'

      - name: Setup Environment for Node
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=node"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicNode"

      - name: Run E2E tests (Node)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'AzureStorage!=Skip&Node!=Skip&Node-AzureStorage!=Skip'

  e2e-azurestorage-windows:
    runs-on: windows-latest
    env:
      E2E_TEST_DURABLE_BACKEND: 'AzureStorage'
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Set up Node.js (needed for Azurite)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Azurite requires at least Node 18
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup E2E tests
        shell: pwsh
        run: |
          .\test\e2e\Tests\build-e2e-test.ps1

      - name: Build Test Project
        working-directory: test/e2e/Tests
        run: dotnet build

      - name: Setup Environment for dotnet
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=dotnet-isolated"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicDotNetIsolated"

      - name: Run E2E tests (dotnet-isolated)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'AzureStorage!=Skip&Dotnet!=Skip&Dotnet-AzureStorage!=Skip'

      - name: Setup Environment for PowerShell
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=powershell"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicPowerShell"

      - name: Run E2E tests (PowerShell)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'AzureStorage!=Skip&PowerShell!=Skip&PowerShell-AzureStorage!=Skip'

      - name: Setup Environment for Python
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=python"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicPython"

      - name: Run E2E tests (Python)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'AzureStorage!=Skip&Python!=Skip&Python-AzureStorage!=Skip'

      - name: Setup Environment for Node
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=node"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicNode"

      - name: Run E2E tests (Node)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'AzureStorage!=Skip&Node!=Skip&Node-AzureStorage!=Skip'

  e2e-mssql:
    runs-on: ubuntu-latest
    env:
      E2E_TEST_DURABLE_BACKEND: "MSSQL"
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Set up Node.js (needed for Azurite)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Azurite requires at least Node 18
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Initialize Environment Variables
        run: | 
          echo "MSSQL_SA_PASSWORD=TEST12_$(echo $RANDOM)!" >> $GITHUB_ENV

      - name: Setup E2E tests
        shell: pwsh
        run: |
          .\test\e2e\Tests\build-e2e-test.ps1 -StartMSSqlContainer

      - name: Build Test Project
        working-directory: test/e2e/Tests
        run: dotnet build

      - name: Setup Environment for dotnet
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=dotnet-isolated"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicDotNetIsolated"

      - name: Run E2E tests (dotnet-isolated)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'MSSQL!=Skip&Dotnet!=Skip&Dotnet-MSSQL!=Skip'

      - name: Setup Environment for PowerShell
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=powershell"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicPowerShell"

      - name: Run E2E tests (PowerShell)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'MSSQL!=Skip&PowerShell!=Skip&PowerShell-MSSQL!=Skip'

      - name: Setup Environment for Python
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=python"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicPython"

      - name: Run E2E tests (Python)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'MSSQL!=Skip&Python!=Skip&Python-MSSQL!=Skip'

      - name: Setup Environment for Node
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=node"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicNode"

      - name: Run E2E tests (Node)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'MSSQL!=Skip&Node!=Skip&Node-MSSQL!=Skip'

  e2e-dts:
    runs-on: ubuntu-latest
    env:
      E2E_TEST_DURABLE_BACKEND: "azureManaged"
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Set up Node.js (needed for Azurite)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Azurite requires at least Node 18
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup E2E tests
        shell: pwsh
        run: |
          .\test\e2e\Tests\build-e2e-test.ps1 -StartDTSContainer

      - name: Build Test Project
        working-directory: test/e2e/Tests
        run: dotnet build

      - name: Setup Environment for dotnet
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=dotnet-isolated"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicDotNetIsolated"

      - name: Run E2E tests (dotnet-isolated)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'DTS!=Skip&Dotnet!=Skip&Dotnet-DTS!=Skip'

      - name: Setup Environment for PowerShell
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=powershell"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicPowerShell"

      - name: Run E2E tests (PowerShell)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'DTS!=Skip&PowerShell!=Skip&PowerShell-DTS!=Skip'

      - name: Setup Environment for Python
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=python"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicPython"

      - name: Run E2E tests (Python)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'DTS!=Skip&Python!=Skip&Python-DTS!=Skip'

      - name: Setup Environment for Node
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "E2E_TEST_FUNCTIONS_LANGUAGE=node"
          Add-Content -Path $env:GITHUB_ENV -Value "TEST_APP_NAME=BasicNode"

      - name: Run E2E tests (Node)
        working-directory: test/e2e/Tests
        run: dotnet test --filter 'DTS!=Skip&Node!=Skip&Node-DTS!=Skip'
